
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fallback for prisma generate when .env is not present (e.g. CI, fresh clone)
    url: process.env.DATABASE_URL ?? "postgresql://localhost:5432/organizer1st",
  },
});
