-- AlterTable
ALTER TABLE "VenueMap" ADD COLUMN "gridCols" INTEGER NOT NULL DEFAULT 24;
ALTER TABLE "VenueMap" ADD COLUMN "gridRows" INTEGER NOT NULL DEFAULT 24;
ALTER TABLE "VenueMap" ADD COLUMN "stageX" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "VenueMap" ADD COLUMN "stageY" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "VenueMap" ADD COLUMN "stageWidth" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "VenueMap" ADD COLUMN "stageHeight" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Section" ADD COLUMN "posX" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Section" ADD COLUMN "posY" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Table" ADD COLUMN "posX" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Table" ADD COLUMN "posY" INTEGER NOT NULL DEFAULT 0;
